"""Write VALIDATION_REPORT.md: source manifest, counts, completeness, eligible depth and unresolved fields.

Usage: python audit_report.py ../data/sheets ../VALIDATION_REPORT.md
"""

import csv
import glob
import os
import statistics
import sys
from collections import Counter

POSITIONS = ["qb", "rb", "wr", "te", "k", "def"]
DECADES = range(1950, 2000, 10)


def load(sheets, pos):
    rows = []
    for f in sorted(glob.glob(os.path.join(sheets, f"{pos}_gamelogs_19*s.csv"))):
        rows += list(csv.DictReader(open(f)))
    return rows


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main(sheets, out_path):
    data = {p: load(sheets, p) for p in POSITIONS}
    reg = {p: [x for x in rows if x["playoff"] == "False"] for p, rows in data.items()}
    key = lambda p: "team" if p == "def" else "player_id"
    md = []
    w = md.append

    w("# Validation report: Fantasy Legends game logs (1950–1999)\n")
    w("Generated by `scripts/audit_report.py` from the CSVs in `data/sheets/`. Every number below is computed "
      "from those files.\n")

    w("## Sources and documented reuse terms\n")
    w("Checked October 2026 from each source's own pages. Being able to download something isn't permission to "
      "republish it.\n")
    w(table(["Dataset", "Used for", "Documented terms", "Status"], [
        ["Pro-Football-Reference / Sports Reference (origin of the base data) — "
         "[Terms of Use](https://www.sports-reference.com/termsofuse.html) (updated 2023-05-19), "
         "[Data Use](https://www.sports-reference.com/data_use.html)",
         "All base stats, 1950–1999 (via the Kaggle scrape below)",
         "Personal, non-transferable license; no scripts, bots or scrapers; no creating a database that competes with "
         "or substitutes for the site; some datasets can't be redistributed at all; asks that people not build sites or "
         "tools from scraped data. Single facts aren't copyrightable, and sharing data from individual pages with credit "
         "is welcome.",
         "**Republishing this dataset is likely not permitted.** Needs the owner's review and, if it matters, legal advice "
         "or written permission from Sports Reference."],
        ["Kaggle `zynicide/nfl-football-player-stats` — "
         "[dataset](https://www.kaggle.com/datasets/zynicide/nfl-football-player-stats)",
         "The file actually downloaded (scraped Dec 2017)",
         "No license listed on the dataset (Kaggle API returns none).",
         "**No grant of rights.** It's a scrape of Sports Reference, so their terms are the relevant ones."],
        ["Scraper `zackthoutt/nfl-player-stats` — [repo](https://github.com/zackthoutt/nfl-player-stats), "
         "[LICENSE](https://github.com/zackthoutt/nfl-player-stats/blob/master/LICENSE)",
         "Field definitions only", "MIT license, covering the code.", "Fine for the code; says nothing about the data."],
        ["nflverse player_stats_1999, play_by_play_1999, players — "
         "[releases](https://github.com/nflverse/nflverse-data/releases)",
         "1999 two-point conversions, recovery TDs, FG distances, DEF fumble recoveries, safeties, blocks, defensive TDs",
         "The nflverse-data repository lists no license. nflverse's nflreadr package says its code is MIT and that "
         "\"NFL data accessed by this package belong to their respective owners, and are governed by their terms of use\" "
         "([nflreadr README](https://github.com/nflverse/nflreadr#readme)).",
         "**Uncertain.** nflverse doesn't grant rights to the data; the underlying owner's terms (presumably the NFL's) apply "
         "and weren't reviewed."],
        ["NFL rule: two-point conversion adopted 1994", "two_pt = 0 for 1950–1993 NFL games", "A fact; no data reused.", "OK"],
    ]))
    w("\nThis repository is public, so the derived files are currently published. Every derived value is traceable "
      "through the `source` column and `data/sheets/corrections_log.csv`.\n")

    w("## Row counts and integrity\n")
    rows = []
    for p in POSITIONS:
        ids = Counter((x[key(p)], x["date"]) for x in data[p])
        rows.append([p.upper(), len(data[p]), len(reg[p]), len(data[p]) - len(reg[p]), sum(v > 1 for v in ids.values())])
    w(table(["Position", "All games", "Regular season", "Playoffs", "Duplicate identity/date"], rows))
    games = Counter(x["game_id"] for x in data["def"])
    linked = {p: sum(x["game_id"] in games for x in data[p]) for p in POSITIONS if p != "def"}
    w(f"\n`game_id` (YYYYMMDD-AWAY-HOME): {len(games)} games, each listed by both teams "
      f"({sum(v == 2 for v in games.values())} of {len(games)}). Player rows whose `game_id` matches a team game: "
      + ", ".join(f"{p.upper()} {n}/{len(data[p])}" for p, n in linked.items()) + ".\n")

    w("## Coverage by decade (regular season)\n")
    w("For each scoring field: **all** = known for every game in the decade, **none** = known for no game, "
      "otherwise the share of games where it's known (usually 1999 only). A field the source shows as 0 but never "
      "actually records is treated as unknown.\n")
    FIELDS = {
        "QB / RB / WR / TE": ("qb", "rb", "wr", "te"), "K": ("k",), "DEF": ("def",)}
    SCORE = {
        "QB / RB / WR / TE": ["pass_yds", "pass_td", "pass_int", "rush_yds", "rush_td", "rec", "rec_yds", "rec_td",
                              "ret_td", "two_pt", "fum_rec_td"],
        "K": ["fgm", "xpm", "fg_missed", "fgm_0_39", "fgm_40_49", "fgm_50p"],
        "DEF": ["pts_allowed", "sacks", "def_int", "fum_rec", "safeties", "blk_punt", "blk_fg", "blk_xp",
                "def_int_td", "def_fum_td", "ret_td"]}
    common = {}
    for group, poss in FIELDS.items():
        rows_g = [x for p in poss for x in reg[p]]
        out = []
        for c in SCORE[group]:
            cells = []
            for d in DECADES:
                r = [x for x in rows_g if d <= int(x["season"]) < d + 10]
                if not r:
                    cells.append("–")
                    continue
                known = sum(x[c] != "" for x in r)
                if c == "def_int":
                    known = sum(x["int_check"] == "match" for x in r)
                cells.append("all" if known == len(r) else "none" if known == 0 else f"{100 * known / len(r):.0f}%")
            out.append([c] + cells)
            common[(group, c)] = cells
        w(f"\n**{group}**\n")
        w(table(["Field"] + [f"{d}s" for d in DECADES], out))
    w("\nFor DEF, `def_int` counts as known only where defenders' and passers' counts agree.\n")
    w("\n**Fields available for every game, 1960–1999** (a consistent Historical-mode rule set):\n")
    for group in FIELDS:
        ok = [c for c in SCORE[group] if all(v == "all" for v in common[(group, c)][1:])]
        no = [c for c in SCORE[group] if c not in ok]
        w(f"- **{group}:** {', '.join(ok)}. Not consistently available: {', '.join(no)}.")
    w("\nThe 1950s also lack return TDs (all positions) and all kicking stats; the AFL (1960–69) and 1994–98 lack "
      "two-point conversions; DEF sacks start in 1982. For DEF interceptions, see the reconciliation section.\n")

    w("## Scoring fields checked\n")
    w("A game counts as known only when every field that earns points for that position is known "
      "(deck v4; fumbles lost score 0, targets and times sacked don't score):\n")
    w("- **QB, RB, WR, TE:** pass_yds, pass_td, pass_int, rush_yds, rush_td, rec, rec_yds, rec_td, ret_td, two_pt, fum_rec_td\n"
      "- **K:** xpm, fgm_0_39, fgm_40_49, fgm_50p, fg_missed (blocked attempts count as misses)\n"
      "- **DEF:** pts_allowed, sacks, def_int, fum_rec, safeties, blk_punt, blk_fg, blk_xp, def_int_td, def_fum_td, ret_td; "
      "a disputed interception count also counts as unknown\n")
    w("`scoring_missing` lists every unknown scoring field on the row. The source has no blank stat values, so "
      "everything not listed is a recorded number.\n")

    w("## Two eligibility options (owner's decision)\n")
    w("- **Strict** (`strict_eligible`, same as `scoring_complete`): every scoring field is known.\n"
      "- **Era-scored** (`era_scored_eligible`): unknown fields are allowed only when the source records that field "
      "for no game in that era; those fields are listed in `era_excluded_fields` and left out of scoring for everyone in "
      "the era. Nothing is filled in. Any other unknown field blocks the game (`era_blocking_fields`).\n")
    w("Era-wide unrecorded fields: fum_rec_td before 1999; ret_td before 1960; two_pt in AFL games (1960–69) and "
      "1994–98; FG distance 1960–98; DEF sacks before 1982; DEF fumble recoveries, safeties, blocks, INT-return and "
      "fumble-return TDs before 1999. Not excludable: "
      "all 1950s kicking (nothing to score), disputed interceptions, and the 1999 game missing from nflverse.\n")
    rows = []
    for p in POSITIONS:
        strict = Counter(int(x["season"]) // 10 * 10 for x in reg[p] if x["strict_eligible"] == "True")
        era = Counter(int(x["season"]) // 10 * 10 for x in reg[p] if x["era_scored_eligible"] == "True")
        total = Counter(int(x["season"]) // 10 * 10 for x in reg[p])
        rows.append([p.upper()] + [f"{strict[d]} / {era[d]} / {total[d]}" for d in DECADES])
    w("Regular-season games, strict / era-scored / total:\n")
    w(table(["Position"] + [f"{d}s" for d in DECADES], rows))
    w("\nWhat blocks each option (regular-season games):\n")
    rows = []
    for p in POSITIONS:
        c = Counter(f for x in reg[p] for f in x["scoring_missing"].split(";") if f)
        b = Counter(f for x in reg[p] for f in x["era_blocking_fields"].split(";") if f)
        rows.append([p.upper(), ", ".join(f"{f} ({n})" for f, n in c.most_common()) or "none",
                     ", ".join(f"{f} ({n})" for f, n in b.most_common()) or "none"])
    w(table(["Position", "Strict: unknown scoring fields", "Era-scored: blocking fields"], rows))

    w("\n## Eligible depth for a 17-week season\n")
    rows = []
    for p in POSITIONS:
        strict = Counter(x[key(p)] for x in reg[p] if x["strict_eligible"] == "True")
        era = Counter(x[key(p)] for x in reg[p] if x["era_scored_eligible"] == "True")
        n = len({x[key(p)] for x in reg[p]})
        rows.append([p.upper(), sum(v >= 17 for v in strict.values()), sum(v >= 17 for v in era.values()), n])
    w(table(["Position", "≥17 games, strict", "≥17 games, era-scored", "Players / team codes"], rows))
    w("\nUnder strict rules no one reaches 17: the extra fields exist only for 1999, a 16-game season. Era-scored "
      "kickers still need a rule for field goals of unknown distance (`fgm` is known, the tier isn't); "
      "`fpts_k_contract` stays blank for them.\n")

    w("## Worked example: Montana, 1989-09-10, SFO at IND (`19890910-SFO-IND`)\n")
    m = next(x for x in data["qb"] if x["game_id"] == "19890910-SFO-IND" and x["name"] == "Joe Montana")
    w(f"Stat line: {m['pass_cmp']}/{m['pass_att']}, {m['pass_yds']} pass yds, {m['pass_td']} TD, {m['pass_int']} INT; "
      f"{m['rush_att']} rushes for {m['rush_yds']} yds, {m['rush_td']} TD; {m['rec']} rec; {m['ret_td']} return TD; "
      f"two_pt {m['two_pt']} (source {m['source']}); fum_rec_td {m['fum_rec_td'] or 'unknown'}. Final {m['team_score']}-{m['opp_score']}.\n")
    w(table(["Option", "Eligible", "Why", "Fields scored"], [
        ["Strict", m["strict_eligible"], f"scoring_missing = {m['scoring_missing']}", "not drawn"],
        ["Era-scored", m["era_scored_eligible"], f"era_excluded_fields = {m['era_excluded_fields']} (unrecorded for all 1950–98 games)",
         "all offense fields except fum_rec_td"],
    ]))
    w(f"\nUnder this dataset's standard formula (0.04/pass yd, 4/pass TD, −2/INT, 0.1/rush yd) the line is "
      f"{m['fpts_std']} points; the site's v4 offense coefficients come from its own code.\n")

    w("## What the unfillable fields are worth\n")
    w("Measured on 1999 regular-season games, where they're known:\n")
    rows = []
    y99 = lambda p: [x for x in reg[p] if x["season"] == "1999" and x["scoring_complete"] == "True"]
    for p in ["qb", "rb", "wr", "te"]:
        r = y99(p)
        extra = [2 * int(x["two_pt"]) + 6 * int(x["fum_rec_td"]) for x in r]
        rows.append([p.upper(), "two_pt, fum_rec_td", f"{statistics.mean(extra):.3f}",
                     f"{sum(e > 0 for e in extra)} of {len(r)}", f"{statistics.mean(float(x['fpts_ppr']) for x in r):.1f}"])
    r = y99("k")
    rows.append(["K", "distance bonus (4/5 vs 3)", f"{statistics.mean(int(x['fgm_40_49']) + 2 * int(x['fgm_50p']) for x in r):.2f}",
                 f"{sum(int(x['fgm_40_49']) + int(x['fgm_50p']) > 0 for x in r)} of {len(r)}",
                 f"{statistics.mean(float(x['fpts_k_contract']) for x in r):.1f}"])
    r = y99("def")
    extra = [2 * (int(x["fum_rec"]) + int(x["safeties"]) + int(x["blk_punt"]) + int(x["blk_fg"]) + int(x["blk_xp"]))
             + 6 * (int(x["def_fum_td"]) + int(x["def_int_td"])) for x in r]
    rows.append(["DEF", "fum_rec, safeties, blocks, def_int_td, def_fum_td", f"{statistics.mean(extra):.2f}",
                 f"{sum(e > 0 for e in extra)} of {len(r)}", f"{statistics.mean(float(x['fpts']) for x in r):.1f}"])
    w(table(["Position", "Fields", "Avg pts/game", "Games where nonzero", "Avg game total"], rows))

    w("\n## Defense interception reconciliation\n")
    c = Counter(x["int_check"] for x in data["def"])
    by_decade = Counter(int(x["season"]) // 10 * 10 for x in data["def"] if x["int_check"] != "match")
    w(f"- Defenders' INTs equal the opposing passers' INTs thrown: {c['match']} games.\n"
      f"- Disagree: {c['raised_to_opp_qb_count'] + c['kept_defender_count']} games "
      f"({', '.join(f'{d}s {by_decade[d]}' for d in DECADES)}). `def_int` holds the larger count, which is a heuristic; "
      "these games are marked `def_int` in `scoring_missing` until verified.\n"
      "- Season checks against published totals: 1985 CHI 34, 1975 PIT 27, 1969 MIN 30, 1961 SDG 49 (all match).\n")

    w("## Unresolved fields\n")
    w(table(["Field", "Positions", "Known for", "Unknown for", "Why"], [
        ["fum_rec_td (offensive fumble-recovery TD)", "QB RB WR TE", "1999", "1950–1998", "Not in the scraped source"],
        ["two_pt", "QB RB WR TE", "NFL 1950–1993 (rule: 0), 1999", "AFL 1960–69, 1994–1998", "Not in the scraped source"],
        ["FG made by distance", "K", "1999", "1960–1998", "Not in the scraped source"],
        ["All kicking stats", "K", "1960–1999", "1950–1959", "Source has almost none before 1960"],
        ["fum_rec, blocked punts/FGs/PATs, def_fum_td", "DEF", "1999", "1950–1998", "Not in the scraped source"],
        ["sacks", "DEF", "1982–1999", "1950–1981", "Not an official stat before 1982"],
        ["safeties, INT-return TDs", "DEF", "1999", "1950–1998", "Source shows 0 but never records them"],
        ["return TDs", "all", "1960–1999", "1950–1959", "Source has almost no return data before 1960"],
        ["def_int", "DEF", "games where both logs agree", f"{c['raised_to_opp_qb_count'] + c['kept_defender_count']} games", "Defender and passer logs disagree"],
        ["1999-09-12 BAL at STL extras", "all", "", "that game", "Missing from nflverse play-by-play"],
    ]))
    w("\nFilling these would need box-score or play-by-play data for 1950–1998. Pro-Football-Reference blocks "
      "automated access from this environment, and how far back its box scores carry each field, and whether "
      "its terms allow reuse, are unverified.\n")

    w("## Decisions for the owner\n")
    w("1. **Strict vs era-scored.** Strict leaves no season playable before 1999. Era-scoring leaves out fields "
      "worth under 0.1 pt/game for skill players, about 0.6 for kickers and more for defenses (see above; measured on 1999). "
      "Era-scored kickers also need a rule for field goals of unknown distance.\n"
      "2. **Defense interceptions.** Accept max(defenders, passers) for the disputed games, or quarantine those games.\n"
      "3. **Reuse rights.** The base data is scraped from Sports Reference and has no stated license, and this "
      "repository is public. Decide whether that's acceptable before publishing.\n")

    with open(out_path, "w") as f:
        f.write("\n".join(md))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main(*sys.argv[1:3])
