"""Write VALIDATION_REPORT.md: source manifest, counts, completeness, eligible depth and unresolved fields.

Usage: python audit_report.py ../data/sheets ../VALIDATION_REPORT.md
"""

import csv
import glob
import os
import statistics
import sys
from collections import Counter

POSITIONS = ["qb", "rb", "wr", "te", "k", "def"]
DECADES = range(1950, 2000, 10)


def load(sheets, pos):
    rows = []
    for f in sorted(glob.glob(os.path.join(sheets, f"{pos}_gamelogs_19*s.csv"))):
        rows += list(csv.DictReader(open(f)))
    return rows


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main(sheets, out_path):
    data = {p: load(sheets, p) for p in POSITIONS}
    reg = {p: [x for x in rows if x["playoff"] == "False"] for p, rows in data.items()}
    key = lambda p: "team" if p == "def" else "player_id"
    md = []
    w = md.append

    w("# Validation report: Fantasy Legends game logs (1950–1999)\n")
    w("Generated by `scripts/audit_report.py` from the CSVs in `data/sheets/`. Every number below is computed "
      "from those files.\n")

    w("## Sources and documented reuse terms\n")
    w("Checked October 2026 from each source's own pages. Being able to download something isn't permission to "
      "republish it.\n")
    w(table(["Dataset", "Used for", "Documented terms", "Status"], [
        ["Pro-Football-Reference / Sports Reference (origin of the base data) — "
         "[Terms of Use](https://www.sports-reference.com/termsofuse.html) (updated 2023-05-19), "
         "[Data Use](https://www.sports-reference.com/data_use.html)",
         "All base stats, 1950–1999 (via the Kaggle scrape below)",
         "Personal, non-transferable license; no scripts, bots or scrapers; no creating a database that competes with "
         "or substitutes for the site; some datasets can't be redistributed at all; asks that people not build sites or "
         "tools from scraped data. Single facts aren't copyrightable, and sharing data from individual pages with credit "
         "is welcome.",
         "**Republishing this dataset is likely not permitted.** Needs the owner's review and, if it matters, legal advice "
         "or written permission from Sports Reference."],
        ["Kaggle `zynicide/nfl-football-player-stats` — "
         "[dataset](https://www.kaggle.com/datasets/zynicide/nfl-football-player-stats)",
         "The file actually downloaded (scraped Dec 2017)",
         "No license listed on the dataset (Kaggle API returns none).",
         "**No grant of rights.** It's a scrape of Sports Reference, so their terms are the relevant ones."],
        ["Scraper `zackthoutt/nfl-player-stats` — [repo](https://github.com/zackthoutt/nfl-player-stats), "
         "[LICENSE](https://github.com/zackthoutt/nfl-player-stats/blob/master/LICENSE)",
         "Field definitions only", "MIT license, covering the code.", "Fine for the code; says nothing about the data."],
        ["nflverse player_stats_1999, play_by_play_1999, players — "
         "[releases](https://github.com/nflverse/nflverse-data/releases)",
         "1999 two-point conversions, recovery TDs, FG distances, DEF fumble recoveries, safeties, blocks, defensive TDs",
         "The nflverse-data repository lists no license. nflverse's nflreadr package says its code is MIT and that "
         "\"NFL data accessed by this package belong to their respective owners, and are governed by their terms of use\" "
         "([nflreadr README](https://github.com/nflverse/nflreadr#readme)).",
         "**Uncertain.** nflverse doesn't grant rights to the data; the underlying owner's terms (presumably the NFL's) apply "
         "and weren't reviewed."],
        ["NFL rule: two-point conversion adopted 1994", "two_pt = 0 for 1950–1993 NFL games", "A fact; no data reused.", "OK"],
    ]))
    w("\nThis repository is public, so the derived files are currently published. Every derived value is traceable "
      "through the `source` column and `data/sheets/corrections_log.csv`.\n")

    w("## Row counts and integrity\n")
    rows = []
    for p in POSITIONS:
        ids = Counter((x[key(p)], x["date"]) for x in data[p])
        rows.append([p.upper(), len(data[p]), len(reg[p]), len(data[p]) - len(reg[p]), sum(v > 1 for v in ids.values())])
    w(table(["Position", "All games", "Regular season", "Playoffs", "Duplicate identity/date"], rows))
    games = Counter(x["game_id"] for x in data["def"])
    linked = {p: sum(x["game_id"] in games for x in data[p]) for p in POSITIONS if p != "def"}
    w(f"\n`game_id` (YYYYMMDD-AWAY-HOME): {len(games)} games, each listed by both teams "
      f"({sum(v == 2 for v in games.values())} of {len(games)}). Player rows whose `game_id` matches a team game: "
      + ", ".join(f"{p.upper()} {n}/{len(data[p])}" for p, n in linked.items()) + ".\n")

    w("## Coverage by decade (regular season)\n")
    w("For each scoring field: **all** = known for every game in the decade, **all but N** = unknown for only N games "
      "(quarantined source conflicts), **none** = known for no game, otherwise the share of games where it's known "
      "(usually 1999 only). A field the source shows as 0 but never actually records is treated as unknown.\n")
    FIELDS = {
        "QB / RB / WR / TE": ("qb", "rb", "wr", "te"), "K": ("k",), "DEF": ("def",)}
    SCORE = {
        "QB / RB / WR / TE": ["pass_yds", "pass_td", "pass_int", "rush_yds", "rush_td", "rec", "rec_yds", "rec_td",
                              "ret_td", "two_pt", "fum_rec_td"],
        "K": ["fgm", "xpm", "fg_missed", "fgm_0_39", "fgm_40_49", "fgm_50p"],
        "DEF": ["pts_allowed", "sacks", "def_int", "fum_rec", "safeties", "blk_punt", "blk_fg", "blk_xp",
                "def_int_td", "def_fum_td", "ret_td", "st_other_td"]}
    common = {}
    for group, poss in FIELDS.items():
        rows_g = [x for p in poss for x in reg[p]]
        out = []
        for c in SCORE[group]:
            cells = []
            for d in DECADES:
                r = [x for x in rows_g if d <= int(x["season"]) < d + 10]
                if not r:
                    cells.append("–")
                    continue
                known = sum(x[c] != "" for x in r)
                if c == "def_int":
                    known = sum(x["int_check"] == "match" for x in r)
                # Floor the share so nothing short of complete reads as 100%.
                cells.append("all" if known == len(r) else "none" if known == 0 else
                             f"all but {len(r) - known}" if len(r) - known <= 10 else f"{100 * known // len(r)}%")
            out.append([c] + cells)
            common[(group, c)] = cells
        w(f"\n**{group}**\n")
        w(table(["Field"] + [f"{d}s" for d in DECADES], out))
    w("\nFor DEF, `def_int` counts as known only where defenders' and passers' counts agree.\n")
    w("\n**Fields available for every game, 1960–1999** (a consistent Historical-mode rule set):\n")
    for group in FIELDS:
        ok = [c for c in SCORE[group] if all(v.startswith("all") for v in common[(group, c)][1:])]
        no = [c for c in SCORE[group] if c not in ok]
        but = [c for c in ok if any(v != "all" for v in common[(group, c)][1:])]
        w(f"- **{group}:** {', '.join(ok) or 'none'}" + (f" ({', '.join(but)}: except a few quarantined games)" if but else "")
          + f". Not consistently available: {', '.join(no) or 'none'}.")
    w("\nThe 1950s also lack return TDs (all positions) and all kicking stats; the AFL (1960–69) and 1994–98 lack "
      "two-point conversions; DEF sacks start in 1982. For DEF interceptions, see the reconciliation section.\n")

    w("## Scoring fields checked\n")
    w("A game counts as known only when every field that earns points for that position is known "
      "(deck v4; fumbles lost score 0, targets and times sacked don't score):\n")
    w("- **QB, RB, WR, TE:** pass_yds, pass_td, pass_int, rush_yds, rush_td, rec, rec_yds, rec_td, ret_td, two_pt, fum_rec_td\n"
      "- **K:** xpm, xp_missed, fgm_0_39, fgm_40_49, fgm_50p, fg_missed (blocked attempts count as misses), plus the kicker's own offense fields\n"
      "- **DEF:** pts_allowed, sacks, def_int, fum_rec, safeties, blk_punt, blk_fg, blk_xp, def_int_td, def_fum_td, ret_td, "
      "st_other_td (special-teams TDs that aren't kick or punt returns: blocked punt/FG returns and the kicking team "
      "scoring on the returner's fumble); a disputed or uncheckable interception count also counts as unknown\n")
    w("`scoring_missing` lists every unknown scoring field on the row. The source has no blank stat values, so "
      "everything not listed is a recorded number.\n")

    w("## Two eligibility options (owner's decision)\n")
    w("- **Strict** (`strict_eligible`, same as `scoring_complete`): every scoring field is known.\n"
      "- **Era-scored** (`era_scored_eligible`): unknown fields are allowed only when the source records that field "
      "for no game in that era; those fields are listed in `era_excluded_fields` and left out of scoring for everyone in "
      "the era. Nothing is filled in. Any other unknown field blocks the game (`era_blocking_fields`). Both options check "
      "every scoring field for the position, kickers' missed extra points and own offense stats included.\n")
    w("Era-wide unrecorded fields: fum_rec_td before 1999; ret_td before 1960; two_pt in AFL games (1960–69) and "
      "1994–98; FG distance 1960–98; DEF sacks before 1982; DEF fumble recoveries, safeties, blocks, INT-return, "
      "fumble-return and other special-teams TDs before 1999. Not excludable (they block both options): "
      "all 1950s kicking (nothing to score); kicking lines the final score shows are missing a kick; missed extra "
      "points where a TD has no recorded PAT try; the five 1999 kicker-games the two sources credit to different "
      "kickers; disputed or unverified interceptions; and the 1999 game missing from nflverse.\n")
    rows = []
    for p in POSITIONS:
        strict = Counter(int(x["season"]) // 10 * 10 for x in reg[p] if x["strict_eligible"] == "True")
        era = Counter(int(x["season"]) // 10 * 10 for x in reg[p] if x["era_scored_eligible"] == "True")
        total = Counter(int(x["season"]) // 10 * 10 for x in reg[p])
        rows.append([p.upper()] + [f"{strict[d]} / {era[d]} / {total[d]}" for d in DECADES])
    w("Regular-season games, strict / era-scored / total:\n")
    w(table(["Position"] + [f"{d}s" for d in DECADES], rows))
    w("\nWhat blocks each option (regular-season games):\n")
    rows = []
    for p in POSITIONS:
        c = Counter(f for x in reg[p] for f in x["scoring_missing"].split(";") if f)
        b = Counter(f for x in reg[p] for f in x["era_blocking_fields"].split(";") if f)
        rows.append([p.upper(), ", ".join(f"{f} ({n})" for f, n in c.most_common()) or "none",
                     ", ".join(f"{f} ({n})" for f, n in b.most_common()) or "none"])
    w(table(["Position", "Strict: unknown scoring fields", "Era-scored: blocking fields"], rows))

    w("\n## Eligible depth for a 17-week season\n")
    rows = []
    for p in POSITIONS:
        strict = Counter(x[key(p)] for x in reg[p] if x["strict_eligible"] == "True")
        era = Counter(x[key(p)] for x in reg[p] if x["era_scored_eligible"] == "True")
        n = len({x[key(p)] for x in reg[p]})
        rows.append([p.upper(), sum(v >= 17 for v in strict.values()), sum(v >= 17 for v in era.values()), n])
    w(table(["Position", "≥17 games, strict", "≥17 games, era-scored", "Players / team codes"], rows))
    rows16 = []
    for p in POSITIONS:
        strict = Counter(x[key(p)] for x in reg[p] if x["strict_eligible"] == "True")
        rows16.append([p.upper(), sum(v >= 16 for v in strict.values())])
    w("\nWith one bye per player, 16 games are enough. Players with ≥16 strict-eligible games: "
      + ", ".join(f"{p} {n}" for p, n in rows16) + ".\n")
    w("\nEach player has one bye, so 16 eligible games cover a 17-week season. Era-scored kickers still need a rule "
      "for field goals of unknown distance (`fgm` is known, the tier isn't); `fpts_k_contract` stays blank for them.\n")

    w("## Worked example: Montana, 1989-09-10, SFO at IND (`19890910-SFO-IND`)\n")
    m = next(x for x in data["qb"] if x["game_id"] == "19890910-SFO-IND" and x["name"] == "Joe Montana")
    w(f"Stat line: {m['pass_cmp']}/{m['pass_att']}, {m['pass_yds']} pass yds, {m['pass_td']} TD, {m['pass_int']} INT; "
      f"{m['rush_att']} rushes for {m['rush_yds']} yds, {m['rush_td']} TD; {m['rec']} rec; {m['ret_td']} return TD; "
      f"two_pt {m['two_pt']} (source {m['source']}); fum_rec_td {m['fum_rec_td'] or 'unknown'}. Final {m['team_score']}-{m['opp_score']}.\n")
    offense = ["pass_yds", "pass_td", "pass_int", "rush_yds", "rush_td", "rec", "rec_yds", "rec_td", "ret_td", "two_pt", "fum_rec_td"]
    excluded = [f for f in m["era_excluded_fields"].split(";") if f]
    w(table(["Option", "Eligible", "Why", "Fields scored"], [
        ["Strict", m["strict_eligible"], f"scoring_missing = {m['scoring_missing'] or 'none'}",
         "all offense fields" if m["strict_eligible"] == "True" else "not drawn"],
        ["Era-scored", m["era_scored_eligible"], f"era_excluded_fields = {m['era_excluded_fields'] or 'none'}",
         "all offense fields" + (f" except {', '.join(excluded)}" if excluded else "")],
    ]))
    w(f"\nUnder this dataset's standard formula (0.04/pass yd, 4/pass TD, −2/INT, 0.1/rush yd) the line is "
      f"{m['fpts_std']} points; the site's v4 offense coefficients come from its own code.\n")

    w("## What the unfillable fields are worth\n")
    w("Measured on 1999 regular-season games, where they're known:\n")
    rows = []
    y99 = lambda p: [x for x in reg[p] if x["season"] == "1999" and x["scoring_complete"] == "True"]
    for p in ["qb", "rb", "wr", "te"]:
        r = y99(p)
        extra = [2 * int(x["two_pt"]) + 6 * int(x["fum_rec_td"]) for x in r]
        rows.append([p.upper(), "two_pt, fum_rec_td", f"{statistics.mean(extra):.3f}",
                     f"{sum(e > 0 for e in extra)} of {len(r)}", f"{statistics.mean(float(x['fpts_ppr']) for x in r):.1f}"])
    r = y99("k")
    rows.append(["K", "distance bonus (4/5 vs 3)", f"{statistics.mean(int(x['fgm_40_49']) + 2 * int(x['fgm_50p']) for x in r):.2f}",
                 f"{sum(int(x['fgm_40_49']) + int(x['fgm_50p']) > 0 for x in r)} of {len(r)}",
                 f"{statistics.mean(float(x['fpts_k_contract']) for x in r):.1f}"])
    r = y99("def")
    extra = [2 * (int(x["fum_rec"]) + int(x["safeties"]) + int(x["blk_punt"]) + int(x["blk_fg"]) + int(x["blk_xp"]))
             + 6 * (int(x["def_fum_td"]) + int(x["def_int_td"]) + int(x["st_other_td"])) for x in r]
    rows.append(["DEF", "fum_rec, safeties, blocks, def_int_td, def_fum_td, st_other_td", f"{statistics.mean(extra):.2f}",
                 f"{sum(e > 0 for e in extra)} of {len(r)}", f"{statistics.mean(float(x['fpts']) for x in r):.1f}"])
    w(table(["Position", "Fields", "Avg pts/game", "Games where nonzero", "Avg game total"], rows))

    w("\n## Final-score reconciliation (evidence for zeros)\n")
    w("For each team-game, the final score is compared with every scoring play the source records for that team "
      "(all its players' TDs, XPs, FGs and safeties): residual = score − (6·TD + XP + 3·FG + 2·safety). **SCORE0** "
      "(residual 0): the recorded plays explain the whole score, so no other scoring play happened for that team — no "
      "safety, two-point conversion, defensive or special-teams TD, fumble-recovery TD or (1950s) return TD. SCORE0 "
      "confirms makes only: a missed kick doesn't score, so attempts and misses aren't proven by it. **SCORE2** "
      "(residual 2 in an NFL game, 1960–1993, when no two-point conversion existed, and only when the source records a "
      "PAT attempt for every recorded TD, so the 2 can't be unrecorded extra points): the 2 points are one safety and "
      "no unrecorded TD happened. Other residuals leave the fields unknown. The arithmetic for every team-game is in "
      "`data/sheets/score_reconciliation.csv`.\n")
    recon = list(csv.DictReader(open(os.path.join(sheets, "score_reconciliation.csv"))))
    rc = Counter((int(x["season"]) // 10 * 10, x["result"]) for x in recon if x["playoff"] == "False")
    w(table(["Decade", "SCORE0", "SCORE2", "Not reconciled", "Team-games"],
            [[f"{d}s", rc[(d, "SCORE0")], rc[(d, "SCORE2")],
              sum(v for (dd, k), v in rc.items() if dd == d and k not in ("SCORE0", "SCORE2")),
              sum(v for (dd, _), v in rc.items() if dd == d)] for d in DECADES]))
    conflicts = list(csv.DictReader(open(os.path.join(sheets, "conflicts.csv"))))
    failed = {x["game_id"] + x["player_id_or_team"] for x in conflicts if x["field"] == "final score"}
    d99 = [x for x in data["def"] if x["season"] == "1999"]
    in_pbp = [x for x in d99 if "NFLV1999" in x["source"]]
    closes = sum(x["game_id"] + x["team"] not in failed for x in in_pbp)
    score0 = {x["game_id"] + x["team"] for x in recon if x["season"] == "1999" and x["result"] == "SCORE0"}
    hidden = sum(1 for x in in_pbp if x["game_id"] + x["team"] in score0
                 and (int(x["safeties"]) > int(x["recorded_safeties"])
                      or any(x[f] != "0" for f in ("def_int_td", "def_fum_td", "st_other_td"))))
    w(f"\n**1999 check.** nflverse play-by-play lists every play, so it can account for the whole score. In "
      f"{closes} of {len(in_pbp)} 1999 team-games it does exactly: the source's recorded TDs, XPs and FGs plus the "
      "play-by-play's safeties, two-point conversions and defensive, special-teams and offensive fumble-recovery TDs equal "
      f"the final score, and both sources agree on kick and punt return TDs ({len(d99) - len(in_pbp)} more team-games, "
      "1999-09-12 BAL at STL, aren't in nflverse). Zeros from the play-by-play are used only where this check passes. "
      f"SCORE0 team-games in 1999 where the play-by-play shows a safety or defensive/special-teams TD the source "
      f"doesn't record: {hidden}. "
      "The 1950s reconcile rarely because the source has almost no kicking or return data then, so mostly shutouts "
      "qualify.\n")
    w("**Bias check** (1960–98 regular season, average points in strict-eligible games vs all games):\n")
    rows = []
    for p, col in [("qb", "fpts_ppr"), ("rb", "fpts_ppr"), ("wr", "fpts_ppr"), ("te", "fpts_ppr"), ("k", "fpts_std")]:
        r = [x for x in reg[p] if 1960 <= int(x["season"]) <= 1998 and x[col] != ""]
        allv = [float(x[col]) for x in r]
        sv = [float(x[col]) for x in r if x["strict_eligible"] == "True"]
        rows.append([p.upper(), f"{statistics.mean(allv):.2f}", f"{statistics.mean(sv):.2f}" if sv else "–",
                     f"{100 * (statistics.mean(sv) / statistics.mean(allv) - 1):+.1f}%" if sv else "–", len(sv)])
    w(table(["Position", "All games", "Strict-eligible games", "Difference", "Strict games"], rows))
    w("\nOffense is unbiased. **Kickers are not:** before 1999, distance tiers are known only for games with no field "
      "goal made (all tiers 0), so a Strict kicker pool before 1999 would draw only those low-scoring games. Strict "
      "kickers need an owner decision (for example, Strict kickers from 1999 only).\n")
    w("**Kicker lines are checked by team.** A kicking line counts as known when the team's recorded kicks add up to its "
      "final score in every possible reading. That proves the team's kicking, not which player the source credits: in "
      "1999, where nflverse names the kicker on every play, the source credits kicks to the wrong kicker in 5 of 426 "
      "kicker-games (those five are quarantined). Before 1999 there is no second source to catch this.\n")

    w("\n## Defense interceptions\n")
    c = Counter(x["int_check"] for x in data["def"])
    by_decade = Counter(int(x["season"]) // 10 * 10 for x in data["def"] if x["int_check"] != "match")
    w(f"- Defenders' INTs equal the opposing passers' INTs thrown: {c['match']} games.\n"
      f"- Disputed (`int_check` = disputed): {c['disputed']} games. Unverified (`int_check` = unverified: the source has "
      f"fewer than 10 pass attempts for the opponent in that game, usually because its passer is missing from the source, "
      f"so even a 0 = 0 match proves nothing): {c['unverified']} games. "
      f"Together {c['disputed'] + c['unverified']} ({', '.join(f'{d}s {by_decade[d]}' for d in DECADES)}). "
      "These are **quarantined**: `def_int` is blank, and the original counts are kept in `def_int_defenders`, "
      "`opp_pass_int` and `opp_pass_att`. The larger count is never chosen.\n"
      "- Season checks against published totals: 1985 CHI 34, 1975 PIT 27, 1969 MIN 30 (all match).\n")

    incomplete_k = sum(1 for x in data["k"] if int(x["season"]) >= 1960 and x["fgm"] == "" and "INCOMPLETE" in x["source"])
    w("## Unresolved fields\n")
    w(table(["Field", "Positions", "Known for", "Unknown for", "Why"], [
        ["fum_rec_td (offensive fumble-recovery TD)", "QB RB WR TE K", "1999; SCORE0/SCORE2 games", "other games", "Not in the scraped source"],
        ["two_pt", "QB RB WR TE K", "NFL 1950–1993 (rule: 0), 1999, SCORE0 games", "other AFL and 1994–98 games", "Not in the scraped source"],
        ["FG made by distance", "K", "1999; games with no FG made", "other 1960–1998 games", "Not in the scraped source"],
        ["FG/XP made and tried", "K", "1960–1999; 1950s where recorded or SCORE0",
         f"other 1950s games; {incomplete_k} 1960–99 kicker-games whose team score shows a kick missing from the source; "
         "5 disputed 1999 kicker-games",
         "Source has almost none before 1960; an odd score gap, or a 6-point gap with no PAT try to match it, means a kick "
         "is missing; in 1999 two sources credit some kicks to a different kicker"],
        ["xp_missed", "K", "1960–1999 where every TD has a recorded PAT try", "1950s; games with a TD but no recorded PAT try",
         "A miss doesn't score, so the final score can't prove it"],
        ["fum_rec, blocked punts/FGs/PATs", "DEF", "1999", "1950–1998", "Not in the scraped source; not provable from the score"],
        ["def_int_td, def_fum_td, st_other_td, safeties", "DEF", "1999; SCORE0/SCORE2 games", "other games", "Not in the scraped source"],
        ["sacks", "DEF", "1982–1999", "1950–1981", "Not an official stat before 1982"],
        ["return TDs", "all", "1960–1999; 1950s SCORE0 games", "other 1950s games", "Source has almost no return data before 1960"],
        ["def_int", "DEF", "games where both logs agree", f"{c['disputed'] + c['unverified']} games",
         "Defender and passer logs disagree, or the opponent's passing isn't recorded"],
        ["1999-09-12 BAL at STL extras", "all", "via score reconciliation where it applies", "the rest", "Missing from nflverse play-by-play"],
    ]))
    w("\nEvery remaining gap is listed per game in `data/sheets/unresolved_players.csv` and "
      "`data/sheets/unresolved_defense.csv` (regular season). Every change, with its old value, new value, source URL "
      "and evidence, is in `data/sheets/corrections_log_{qb,rb,wr,te,k,def}.csv`; the same fills in the research "
      "workbook's merge format are in `data/sheets/verified_replacements_{...}.csv`. Filling the rest needs box-score "
      "or play-by-play data for 1950–1998; Pro-Football-Reference blocks automated access from this environment, "
      "and its terms restrict reuse.\n")

    w("## Decisions for the owner\n")
    w("1. **Strict kickers.** Before 1999 only no-field-goal games have distance tiers, a biased pool (see the bias check).\n"
      "2. **Strict defenses** remain 1999-only: fumble recoveries and blocked kicks can't be proven from the score.\n"
      "3. **Historical rules** are unchanged and still pending.\n"
      "4. **Reuse rights.** The base data is scraped from Sports Reference and has no stated license, and this "
      "repository is public.\n"
      "5. **`st_other_td`** (blocked-kick return TDs, the kicking team scoring on a returner's fumble) is now its own DEF "
      "column. It's treated like the other defensive/special-teams TDs (6 points) and is part of Strict completeness; "
      "the importer should map it accordingly.\n"
      "6. **More box-score data.** Pro Football Archives (profootballarchives.com) has per-game box scores for older "
      "seasons that could settle disputed games. Its terms and whether it allows reuse haven't been checked.\n")

    with open(out_path, "w") as f:
        f.write("\n".join(md))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main(*sys.argv[1:3])
