"""Write VALIDATION_REPORT.md: source manifest, counts, completeness, eligible depth and unresolved fields.

Usage: python audit_report.py ../data/sheets ../VALIDATION_REPORT.md
"""

import csv
import glob
import os
import statistics
import sys
from collections import Counter

POSITIONS = ["qb", "rb", "wr", "te", "k", "def"]
DECADES = range(1950, 2000, 10)


def load(sheets, pos):
    rows = []
    for f in sorted(glob.glob(os.path.join(sheets, f"{pos}_gamelogs_19*s.csv"))):
        rows += list(csv.DictReader(open(f)))
    return rows


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main(sheets, out_path):
    data = {p: load(sheets, p) for p in POSITIONS}
    reg = {p: [x for x in rows if x["playoff"] == "False"] for p, rows in data.items()}
    key = lambda p: "team" if p == "def" else "player_id"
    md = []
    w = md.append

    w("# Validation report: Fantasy Legends game logs (1950–1999)\n")
    w("Generated by `scripts/audit_report.py` from the CSVs in `data/sheets/`. Every number below is computed "
      "from those files.\n")

    w("## Source manifest\n")
    w(table(["Source", "URL", "Used for", "Reuse rights"], [
        ["Pro-Football-Reference game logs, scraped Dec 2017 (Kaggle `zynicide/nfl-football-player-stats`)",
         "https://www.kaggle.com/datasets/zynicide/nfl-football-player-stats",
         "All base stats, 1950–1999", "**Unverified.** Kaggle lists no license; the data is scraped from Sports Reference, whose terms apply"],
        ["Scraper for the above", "https://github.com/zackthoutt/nfl-player-stats", "Field definitions", "Code only"],
        ["nflverse player_stats_1999, play_by_play_1999, players",
         "https://github.com/nflverse/nflverse-data/releases", "1999 two-point conversions, recovery TDs, FG distances, DEF fumble recoveries/blocks/fumble-return TDs",
         "**Unverified.** The nflverse-data repository states no license on GitHub; check nflverse's terms"],
        ["NFL rulebook: two-point conversion adopted 1994", "", "two_pt = 0 for 1950–1993 NFL games", "Fact, no data reused"],
    ]))
    w("\nEvery value derived from these sources is traceable through the `source` column and "
      "`data/sheets/corrections_log.csv`. Original values of corrected fields are kept beside them "
      "(`def_int_defenders`, `opp_pass_int`).\n")

    w("## Row counts and integrity\n")
    rows = []
    for p in POSITIONS:
        ids = Counter((x[key(p)], x["date"]) for x in data[p])
        rows.append([p.upper(), len(data[p]), len(reg[p]), len(data[p]) - len(reg[p]), sum(v > 1 for v in ids.values())])
    w(table(["Position", "All games", "Regular season", "Playoffs", "Duplicate identity/date"], rows))
    games = Counter(x["game_id"] for x in data["def"])
    linked = {p: sum(x["game_id"] in games for x in data[p]) for p in POSITIONS if p != "def"}
    w(f"\n`game_id` (YYYYMMDD-AWAY-HOME): {len(games)} games, each listed by both teams "
      f"({sum(v == 2 for v in games.values())} of {len(games)}). Player rows whose `game_id` matches a team game: "
      + ", ".join(f"{p.upper()} {n}/{len(data[p])}" for p, n in linked.items()) + ".\n")

    w("## Scoring completeness (regular season)\n")
    w("`scoring_complete` = every field that carries points under the deck v4 contract is known. "
      "Targets and times sacked don't score, so they don't count against it.\n")
    rows = []
    for p in POSITIONS:
        c = Counter((int(x["season"]) // 10 * 10, x["scoring_complete"] == "True") for x in reg[p])
        rows.append([p.upper()] + [f"{c[(d, True)]} / {c[(d, True)] + c[(d, False)]}" for d in DECADES])
    w(table(["Position"] + [f"{d}s" for d in DECADES], rows))
    w("\nWhat blocks it:\n")
    rows = []
    for p in POSITIONS:
        c = Counter(f for x in reg[p] if x["scoring_complete"] == "False" for f in x["scoring_missing"].split(";") if f)
        rows.append([p.upper(), ", ".join(f"{f} ({n})" for f, n in c.most_common())])
    w(table(["Position", "Missing scoring field (regular-season games)"], rows))

    w("\n## Eligible depth for a 17-week season\n")
    rows = []
    for p in POSITIONS:
        strict = Counter(x[key(p)] for x in reg[p] if x["scoring_complete"] == "True")
        any_games = Counter(x[key(p)] for x in reg[p])
        rows.append([p.upper(), sum(v >= 17 for v in strict.values()), sum(v >= 17 for v in any_games.values()), len(any_games)])
    w(table(["Position", "≥17 scoring-complete games", "≥17 games if era-scored", "Players/teams"], rows))
    w("\nNo player or team reaches 17 scoring-complete games: the extra fields exist only for 1999, a 16-game season. "
      "\"Era-scored\" means fields the source doesn't record for that era are left out of scoring for everyone "
      "in that era (no values are filled in).\n")

    w("## What the unfillable fields are worth\n")
    w("Measured on 1999 regular-season games, where they're known:\n")
    rows = []
    y99 = lambda p: [x for x in reg[p] if x["season"] == "1999" and x["scoring_complete"] == "True"]
    for p in ["qb", "rb", "wr", "te"]:
        r = y99(p)
        extra = [2 * int(x["two_pt"]) + 6 * int(x["fum_rec_td"]) for x in r]
        rows.append([p.upper(), "two_pt, fum_rec_td", f"{statistics.mean(extra):.3f}",
                     f"{sum(e > 0 for e in extra)} of {len(r)}", f"{statistics.mean(float(x['fpts_ppr']) for x in r):.1f}"])
    r = y99("k")
    rows.append(["K", "distance bonus (4/5 vs 3)", f"{statistics.mean(int(x['fgm_40_49']) + 2 * int(x['fgm_50p']) for x in r):.2f}",
                 f"{sum(int(x['fgm_40_49']) + int(x['fgm_50p']) > 0 for x in r)} of {len(r)}",
                 f"{statistics.mean(float(x['fpts_k_contract']) for x in r):.1f}"])
    r = y99("def")
    extra = [2 * (int(x["fum_rec"]) + int(x["blk_punt"]) + int(x["blk_fg"]) + int(x["blk_xp"])) + 6 * int(x["def_fum_td"]) for x in r]
    rows.append(["DEF", "fum_rec, blocks, def_fum_td", f"{statistics.mean(extra):.2f}",
                 f"{sum(e > 0 for e in extra)} of {len(r)}", f"{statistics.mean(float(x['fpts']) for x in r):.1f}"])
    w(table(["Position", "Fields", "Avg pts/game", "Games where nonzero", "Avg game total"], rows))

    w("\n## Defense interception reconciliation\n")
    c = Counter(x["int_check"] for x in data["def"])
    by_decade = Counter(int(x["season"]) // 10 * 10 for x in data["def"] if x["int_check"] != "match")
    w(f"- Defenders' INTs equal the opposing passers' INTs thrown: {c['match']} games.\n"
      f"- Disagree: {c['raised_to_opp_qb_count'] + c['kept_defender_count']} games "
      f"({', '.join(f'{d}s {by_decade[d]}' for d in DECADES)}). `def_int` holds the larger count, which is a heuristic; "
      "these games are marked `def_int` in `scoring_missing` until verified.\n"
      "- Season checks against published totals: 1985 CHI 34, 1975 PIT 27, 1969 MIN 30, 1961 SDG 49 (all match).\n")

    w("## Unresolved fields\n")
    w(table(["Field", "Positions", "Known for", "Unknown for", "Why"], [
        ["fum_rec_td (offensive fumble-recovery TD)", "QB RB WR TE", "1999", "1950–1998", "Not in the scraped source"],
        ["two_pt", "QB RB WR TE", "NFL 1950–1993 (rule: 0), 1999", "AFL 1960–69, 1994–1998", "Not in the scraped source"],
        ["FG made by distance", "K", "1999", "1960–1998", "Not in the scraped source"],
        ["All kicking stats", "K", "1960–1999", "1950–1959", "Source has almost none before 1960"],
        ["fum_rec, blocked punts/FGs/PATs, def_fum_td", "DEF", "1999", "1950–1998", "Not in the scraped source"],
        ["sacks", "DEF", "1982–1999", "1950–1981", "Not an official stat before 1982"],
        ["def_int", "DEF", "games where both logs agree", f"{c['raised_to_opp_qb_count'] + c['kept_defender_count']} games", "Defender and passer logs disagree"],
        ["1999-09-12 BAL at STL extras", "all", "", "that game", "Missing from nflverse play-by-play"],
    ]))
    w("\nFilling these would need box-score or play-by-play data for 1950–1998. Pro-Football-Reference blocks "
      "automated access from this environment, and how far back its box scores carry each field, and whether "
      "its terms allow reuse, are unverified.\n")

    w("## Decisions for the owner\n")
    w("1. **Strict vs era-scored.** Strict completeness leaves no season playable before 1999. Era-scoring "
      "changes skill-position scores by under 0.1 pt/game, kickers by about 0.6, defenses by about 1.9.\n"
      "2. **Defense interceptions.** Accept max(defenders, passers) for the disputed games, or quarantine those games.\n"
      "3. **Reuse rights.** The base data is scraped from Sports Reference and has no stated license, and this "
      "repository is public. Decide whether that's acceptable before publishing.\n")

    with open(out_path, "w") as f:
        f.write("\n".join(md))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main(*sys.argv[1:3])
